name: fitime
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

  #BloC
  flutter_bloc: ^7.0.1

  # Reminder notification
  flutter_local_notifications: ^9.5.3+1

  cupertino_icons: ^1.0.2

  dots_indicator: ^2.0.0

  # Percent circle
  percent_indicator: ^3.0.1

  # Workout Details sliding up panel
  sliding_up_panel: ^2.0.0+1

  # Video player
  video_player: ^2.4.0
  chewie:
    git:
      url: https://github.com/fluttercommunity/chewie.git

  # Countdown timer
  custom_timer: ^0.0.6

  font_awesome_flutter: ^10.1.0

  lottie: ^1.3.0

  # Native timezone
  flutter_native_timezone: ^2.0.0

  # Permission handler
  permission_handler: ^8.1.4+2

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/fitime_playstore.png"


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/home/
    - assets/icons/home/
    - assets/homecards/

    - assets/icons/workouts/
    - assets/videos/workouts/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.otf
          weight: 700
